# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('lastupdateddate', models.CharField(verbose_name='last updated date')),
                ('orgabbrname', models.CharField(max_length=10)),
                ('orgid', models.IntegerField(primary_key=True, serialize=False)),
                ('orgimageurl', models.CharField(max_length=150)),
                ('orgjurisdictiontype', models.CharField(max_length=50)),
                ('orgname', models.CharField(max_length=200)),
                ('orgparentid', models.IntegerField()),
                ('orgtype', models.CharField(max_length=200)),
                ('orgurladdress', models.CharField(max_length=200)),
                ('orgurltext', models.CharField(max_length=200)),
            ],
        ),
    ]
