# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='lastupdateddate',
            field=models.CharField(max_length=100),
        ),
    ]
