# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='Campsite',
        ),
        migrations.DeleteModel(
            name='EntityLink',
        ),
        migrations.DeleteModel(
            name='Facilities',
        ),
        migrations.DeleteModel(
            name='FacilityAddress',
        ),
        migrations.DeleteModel(
            name='PermitEntrance',
        ),
        migrations.DeleteModel(
            name='RecAreaAddress',
        ),
        migrations.DeleteModel(
            name='RecAreas',
        ),
        migrations.DeleteModel(
            name='RecreationalActivity',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
