# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20170306_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='orgid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
