# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20170306_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityLink',
            fields=[
                ('description', models.CharField(max_length=200)),
                ('entityid', models.CharField(max_length=200)),
                ('entitytype', models.CharField(max_length=200)),
                ('linktype', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('facilityadaaccess', models.CharField(max_length=100)),
                ('facilitydescription', models.CharField(max_length=10)),
                ('facilitydirections', models.IntegerField(primary_key=True)),
                ('facilityemail', models.CharField(max_length=150)),
                ('facilityid', models.IntegerField(primary_key=True, serialize=False)),
                ('facilitylatitude', models.CharField(max_length=200)),
                ('facilitylongitude', models.IntegerField()),
                ('facilitymapurl', models.CharField(max_length=200)),
                ('facilityname', models.CharField(max_length=200)),
                ('facilityphone', models.CharField(max_length=200)),
                ('facilityreservationurl', models.CharField(max_length=200)),
                ('facilitytypedescription', models.CharField(max_length=200)),
                ('facilityusefeedescription', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=200)),
                ('lastupdateddate', models.CharField(max_length=200)),
                ('legacyfacilityid', models.CharField(max_length=200)),
                ('orgfacilityid', models.CharField(max_length=200)),
                ('staylimit', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityAddress',
            fields=[
                ('addresscountrycode', models.CharField(max_length=200)),
                ('addressstatecode', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('facilityaddressid', models.IntegerField(primary_key=True, serialize=False)),
                ('facilityaddresstype', models.CharField(max_length=200)),
                ('facilityid', models.CharField(max_length=200)),
                ('facilitystreetaddress1', models.CharField(max_length=200)),
                ('facilitystreetaddress2', models.CharField(max_length=200)),
                ('facilitystreetaddress3', models.CharField(max_length=200)),
                ('postalcode', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RecreationalActivity',
            fields=[
                ('activityid', models.IntegerField(primary_key=True, serialize=False)),
                ('activitylevel', models.CharField(max_length=200)),
                ('activityname', models.CharField(max_length=200)),
                ('activityparentid', models.IntegerField(max_length=200)),
            ],
        ),
    ]
