# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_entitylink_facilities_facilityaddress_recreationalactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='facilitydirections',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='facilitylongitude',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recreationalactivity',
            name='activityparentid',
            field=models.CharField(max_length=200),
        ),
    ]
