# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20170306_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='orgparentid',
            field=models.CharField(max_length=10),
        ),
    ]
