# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20170307_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='facilitydescription',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='facilitydirections',
            field=models.CharField(max_length=100),
        ),
    ]
