# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20170307_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='facilitydescription',
            field=models.CharField(max_length=1000),
        ),
    ]
