# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20170307_1804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntityLink',
        ),
        migrations.DeleteModel(
            name='FacilityAddress',
        ),
        migrations.DeleteModel(
            name='RecreationalActivity',
        ),
        migrations.AddField(
            model_name='facilities',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facilities',
            name='facilityid',
            field=models.IntegerField(max_length=150),
        ),
    ]
