# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_attribute_campsite_entitylink_facilities_facilityaddress_permitentrance_recareaaddress_recreationala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitylink',
            name='entityid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entitylink',
            name='linktype',
            field=models.CharField(max_length=200),
        ),
    ]
