# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20170310_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activitydescription', models.CharField(max_length=200)),
                ('activityfeeddescription', models.CharField(max_length=200)),
                ('activityid', models.CharField(max_length=200)),
                ('entityid', models.CharField(max_length=200)),
                ('entitytype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entityid', models.CharField(max_length=200)),
                ('entitytype', models.CharField(max_length=200)),
                ('eventadaaccess', models.CharField(max_length=200)),
                ('eventagegroup', models.CharField(max_length=200)),
                ('eventcomments', models.CharField(max_length=200)),
                ('eventdescription', models.CharField(max_length=200)),
                ('eventemail', models.CharField(max_length=200)),
                ('eventenddate', models.CharField(max_length=200)),
                ('eventfeeddescription', models.CharField(max_length=200)),
                ('eventfrequencydescription', models.CharField(max_length=200)),
                ('eventid', models.CharField(max_length=200)),
                ('eventname', models.CharField(max_length=200)),
                ('eventregistrationrequired', models.CharField(max_length=200)),
                ('eventscopedescription', models.CharField(max_length=200)),
                ('eventstartdate', models.CharField(max_length=200)),
                ('eventtypedescription', models.CharField(max_length=200)),
                ('eventurladdress', models.CharField(max_length=200)),
                ('eventurltext', models.CharField(max_length=200)),
                ('lastupdateddate', models.CharField(max_length=200)),
                ('sponsorclasstype', models.CharField(max_length=200)),
                ('sponsoremail', models.CharField(max_length=200)),
                ('sponsorname', models.CharField(max_length=200)),
                ('sponsorphone', models.CharField(max_length=200)),
                ('sponsorurladdress', models.CharField(max_length=200)),
                ('sponsorurltext', models.CharField(max_length=200)),
            ],
        ),
    ]
