# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_entityactivities_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('embedcode', models.CharField(max_length=200)),
                ('entityid', models.CharField(max_length=200)),
                ('entitymediaid', models.CharField(max_length=200)),
                ('entitytype', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=200)),
                ('mediatype', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('width', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MemberTours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membertourid', models.CharField(max_length=200)),
                ('tourid', models.CharField(max_length=200)),
                ('tourname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrgEntities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entityid', models.CharField(max_length=200)),
                ('entitytype', models.CharField(max_length=200)),
                ('orgid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PermitEntranceZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permitentranceid', models.CharField(max_length=200)),
                ('permitentrancezoneid', models.CharField(max_length=200)),
                ('zone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PermittedEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campsiteid', models.CharField(max_length=200)),
                ('equipmentname', models.CharField(max_length=200)),
                ('maxlength', models.CharField(max_length=200)),
            ],
        ),
    ]
