# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_media_membertours_orgentities_permitentrancezone_permittedequipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecAreaFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilityid', models.CharField(max_length=200)),
                ('recareaid', models.CharField(max_length=200)),
            ],
        ),
    ]
