# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_recareafacility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='lastupdateddate',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='orgid',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='orgimageurl',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='orgparentid',
            field=models.IntegerField(),
        ),
    ]
