# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20170310_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='orgid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
