# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20170310_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='lastupdateddate',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
