# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_auto_20170310_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilities',
            name='id',
        ),
        migrations.AlterField(
            model_name='facilities',
            name='facilityadaaccess',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='facilitydescription',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='facilitydirections',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='facilityemail',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='facilityid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='facilitylatitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='facilitylongitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='facilitymapurl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='facilityname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='facilityphone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='facilityreservationurl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='facilitytypedescription',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='facilityusefeedescription',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='keywords',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='lastupdateddate',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='legacyfacilityid',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='orgfacilityid',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='staylimit',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
