# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_auto_20170310_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='lastupdateddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='legacyfacilityid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='orgfacilityid',
            field=models.IntegerField(null=True),
        ),
    ]
