# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_auto_20170310_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityaddress',
            name='addresscountrycode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='facilityaddress',
            name='addressstatecode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='facilityaddress',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facilityaddress',
            name='facilityaddresstype',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facilityaddress',
            name='facilityid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='facilityaddress',
            name='facilitystreetaddress1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facilityaddress',
            name='facilitystreetaddress2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facilityaddress',
            name='facilitystreetaddress3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facilityaddress',
            name='postalcode',
            field=models.IntegerField(null=True),
        ),
    ]
